### ISSUE TITLE
Invalid Solr syntax in an ozcam query to biocache-service occurrences/facets/download

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ozcam-hub#6]
The following invalid Solr syntax is showing up in the biocache-service logs with a referrer of ozcam.

```
==> /var/log/tomcat7/biocache-service.log <==
2018-09-21 11:52:06,348 [http-bio-8080-exec-154] DEBUG au.org.ala.biocache.util.QueryFormatUtils  (QueryFormatUtils.java:272) - term query: basis_of_record:"PreservedSpecimen"
2018-09-21 11:52:06,348 [http-bio-8080-exec-154] DEBUG au.org.ala.biocache.util.QueryFormatUtils  (QueryFormatUtils.java:273) - groups: basis_of_record|"PreservedSpecimen"
2018-09-21 11:52:06,349 [http-bio-8080-exec-154] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:2587) - Solr query: qt=standard&facet=true&facet.field=assertions&facet.mincount=1&facet.limit=1000&facet.sort=count&rows=0&start=0&q=*:*&fq=basis_of_record:"PreservedSpecimen"&fq=data_hub_uid:dh1+AND+basis_of_record:&facet.missing=true&sort=score+asc
2018-09-21 11:52:06,349 [http-bio-8080-exec-154] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:3859) - SOLR query:qt=standard&facet=true&facet.field=assertions&facet.mincount=1&facet.limit=1000&facet.sort=count&rows=0&start=0&q=*:*&fq=basis_of_record:"PreservedSpecimen"&fq=data_hub_uid:dh1+AND+basis_of_record:&facet.missing=true&sort=score+asc
2018-09-21 11:52:06,354 [http-bio-8080-exec-154] ERROR org.apache.solr.client.solrj.impl.CloudSolrClient  (CloudSolrClient.java:1167) - Request to collection biocache failed due to (400) org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://aws-sc2b.ala:8983/solr/biocache: org.apache.solr.search.SyntaxError: Cannot parse 'data_hub_uid:dh1 AND basis_of_record:': Encountered "<EOF>" at line 1, column 37.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    "filter(" ...
    <NUMBER> ...
    , retry? 0
2018-09-21 11:52:06,354 [http-bio-8080-exec-154] ERROR au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:3881) - query failed: qt=standard&facet=true&facet.field=assertions&facet.mincount=1&facet.limit=1000&facet.sort=count&rows=0&start=0&q=*:*&fq=basis_of_record:"PreservedSpecimen"&fq=data_hub_uid:dh1+AND+basis_of_record:&facet.missing=true&sort=score+asc&_stateVer_=biocache-2018-09-19-08-45:880 : Error from server at http://aws-sc2b.ala:8983/solr/biocache: org.apache.solr.search.SyntaxError: Cannot parse 'data_hub_uid:dh1 AND basis_of_record:': Encountered "<EOF>" at line 1, column 37.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    "filter(" ...
    <NUMBER> ...
    
2018-09-21 11:52:06,354 [http-bio-8080-exec-154] ERROR au.org.ala.biocache.web.OccurrenceController  (OccurrenceController.java:915) - Error from server at http://aws-sc2b.ala:8983/solr/biocache: org.apache.solr.search.SyntaxError: Cannot parse 'data_hub_uid:dh1 AND basis_of_record:': Encountered "<EOF>" at line 1, column 37.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    "filter(" ...
    <NUMBER> ...
    
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://aws-sc2b.ala:8983/solr/biocache: org.apache.solr.search.SyntaxError: Cannot parse 'data_hub_uid:dh1 AND basis_of_record:': Encountered "<EOF>" at line 1, column 37.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    "filter(" ...
    <NUMBER> ...
    
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:612)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:279)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:268)
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:447)
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:388)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1383)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:1134)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:1073)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:160)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:974)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:990)
	at au.org.ala.biocache.dao.SearchDAOImpl.query(SearchDAOImpl.java:3862)
	at au.org.ala.biocache.dao.SearchDAOImpl.runSolrQuery(SearchDAOImpl.java:2589)
	at au.org.ala.biocache.dao.SearchDAOImpl.writeFacetToStream(SearchDAOImpl.java:771)
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	at com.sun.proxy.$Proxy44.writeFacetToStream(Unknown Source)
	at au.org.ala.biocache.web.OccurrenceController.downloadFacet(OccurrenceController.java:913)
	at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.SimpleCORSFilter.doFilter(SimpleCORSFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.LoggerConfigFilter.doFilter(LoggerConfigFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2018-09-21 11:52:06,354 [http-bio-8080-exec-154] DEBUG au.org.ala.biocache.dao.JsonPersistentQueueDAOImpl  (JsonPersistentQueueDAOImpl.java:231) - Removing the download from the queue
2018-09-21 11:52:06,355 [http-bio-8080-exec-154] INFO au.org.ala.biocache.dao.JsonPersistentQueueDAOImpl  (JsonPersistentQueueDAOImpl.java:236) - Deleting /data/cache/downloads/offline1537494726348.json false

==> /var/log/nginx/access.log <==
REDACTED - - [21/Sep/2018:11:52:06 +1000] "GET /ws/occurrences/facets/download?q=*%3A*&fq=basis_of_record%3A%22PreservedSpecimen%22&qc=data_hub_uid%3Adh1%20AND%20basis_of_record:&quot;PreservedSpecimen&quot;&facets=assertions&count=true&lookup=true HTTP/1.1" 200 0 "https://ozcam.ala.org.au/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "REDACTED"
```

**Comment by ansell** [comment]
Testing with this query URL on the biocache-ws-test server, using percent encoding instead of XML encoded for the fq value does not throw an error:

Buggy query:

``https://biocache-ws-test.ala.org.au/ws/occurrences/facets/download?q=*%3A*&fq=basis_of_record%3A%22PreservedSpecimen%22&qc=data_hub_uid%3Adh1%20AND%20basis_of_record:&quot;PreservedSpecimen&quot;&facets=assertions&count=true&lookup=true``

Working query:

``https://biocache-ws-test.ala.org.au/ws/occurrences/facets/download?q=*%3A*&fq=basis_of_record%3A%22PreservedSpecimen%22&qc=data_hub_uid%3Adh1%20AND%20basis_of_record:%22PreservedSpecimen%22&facets=assertions&count=true&lookup=true``

**Comment by javier-molina** [comment]
Related FD Issue https://support.ehelp.edu.au/a/tickets/23441
